# ************************************************************************
# Product    : Home information and control
# Date       : 2016-12-07
# Copyright  : Copyright (C) 2016 Kjeholt Engineering. All rights reserved.
# Contact    : dev@kjeholt.se
# Url        : http://www-dev.kjeholt.se
# Licence    : ---
# -------------------------------------------------------------------------
# File       : base-mysql-mydumper/Dockerfile-rpi
# Version    : 1.0.0
# Author     : Bjorn Kjeholt
# *************************************************************************
 FROM armbuild/debian:jessie

MAINTAINER Björn Kjeholt <dev@kjeholt.se>

ARG DOCKER_IMAGE_NAME
ARG DOCKER_IMAGE_TAG

ENV DOCKER_IMAGE_NAME ${DOCKER_IMAGE_NAME:-UnknownName}
ENV DOCKER_IMAGE_TAG ${DOCKER_IMAGE_TAG:-UnknownRevision}

#
# Install required packages.
#

RUN apt-get -y update && \
    apt-get -y install  curl \
                        cmake \
                        make \
                        gcc \
                        g++ \
                        libglib2.0-dev \
                        libmysqlclient15-dev \
                        zlib1g-dev \
                        libpcre3-dev \
                        libssl-dev && \
    mkdir -p /usr/local/src/ && \
    mkdir -p /usr/local/bin/ && \
    mkdir -p /etc/ && \
    mkdir -p /backup/files

COPY Source /usr/local/src
WORKDIR /usr/local/src/mydumper

RUN cmake . && \
    make && \
    mv mydumper myloader ../../bin && \
    rm -fr * && \
    apt-get -y remove  cmake \
                       make \
                       gcc \
                       g++ && \
    apt-get -y autoremove && \
    rm -rf /var/lib/apt/lists/*

#
# Install start script.
#

ONBUILD COPY Scripts /usr/local/bin/

ONBUILD RUN chmod -f 755 /usr/local/bin/* 

#
# Set container settings.
#

# VOLUME ["/backup"]
WORKDIR /backup

#
# Start process.
#

ONBUILD CMD ["/usr/local/bin/execute.sh"]
